  
[**Dr. Kevin M. Moerman**](mailto:kevin.moerman@nuigalway.ie), _Lecturer in Biomedical Engineering_   

National University of Ireland Galway.   

---

\newpage

# Learning objectives
At the end of this lecture you should be able to:   

* Derive the finite element equations for thermal problems on 1D linear elastic trusses
* Solve basic thermal problems for linear elastic trusses


# The truss element (mechanical loads)
![spring](truss1.png)  

* Behaviour Hooke's law for a bar:    
$$\begin{Bmatrix} \sigma \end{Bmatrix}=E \begin{Bmatrix}\epsilon\end{Bmatrix}$$     
$$\begin{Bmatrix} f_{1} \\ f_{2} \end{Bmatrix}=\frac{AE}{L}\begin{bmatrix} 1 & -1 \\ -1 & 1\end{bmatrix}\begin{Bmatrix} u_1 \\ u_2\end{Bmatrix}$$   

* Truss (or bar) is a 1D element but has a **cross-sectional area** $A$    

* **strain** a relative metric for deformation: 
$$\begin{Bmatrix} \varepsilon \end{Bmatrix}= \begin{bmatrix} B \end{bmatrix}\begin{Bmatrix} u \end{Bmatrix}$$  


# The truss element (thermal loads)

## Adding termal strain
![spring](truss1.png)   

Define a total strain $\varepsilon_{tot}$  and split into a thermal $\begin{Bmatrix}\varepsilon_{0}\end{Bmatrix}$ and mechanical (elastic) strain $\begin{Bmatrix}\varepsilon_{e}\end{Bmatrix}$: 
$$\begin{Bmatrix}\varepsilon_{tot}\end{Bmatrix}=\begin{Bmatrix}\varepsilon_e\end{Bmatrix}+\begin{Bmatrix}\varepsilon_0\end{Bmatrix}$$
$$\begin{Bmatrix}\varepsilon_e\end{Bmatrix}=\begin{Bmatrix}\varepsilon_{tot}\end{Bmatrix}-\begin{Bmatrix}\varepsilon_{0}\end{Bmatrix}$$    
and 
$$\begin{Bmatrix}\varepsilon_{0}\end{Bmatrix}=\alpha \Delta T \rightarrow \begin{Bmatrix}\varepsilon_{tot}\end{Bmatrix}=\frac{\begin{Bmatrix}\sigma\end{Bmatrix}}{E}+\alpha \Delta T=\begin{bmatrix} B \end{bmatrix}\begin{Bmatrix} u \end{Bmatrix}$$
$\alpha$: Thermal expansion coefficient   
$\Delta T$: Temperature change

## Developing the finite element equations
Using the variational principle, the potential energy of a system can be expressed as:
$$\Pi=\Lambda-W$$
$\Pi$ : Potential energy of the system   
$\Lambda$ : The sum of internal strain energy   
$W$ : Work done by external forces


Recall that the strain energy is derived through integration over the volume but this time features $\begin{Bmatrix}\varepsilon_e\end{Bmatrix}$ instead of $\begin{Bmatrix}\varepsilon\end{Bmatrix}$:   
$$\Lambda=\int_V \frac{\begin{Bmatrix}\sigma\end{Bmatrix} \begin{Bmatrix}\varepsilon_e\end{Bmatrix}}{2} dV$$
Which using
$$\begin{Bmatrix} \sigma \end{Bmatrix}=E \begin{Bmatrix}\varepsilon_e\end{Bmatrix}$$
Leads to
$$\Lambda=\int_V \frac{E\begin{Bmatrix}\varepsilon_e\end{Bmatrix}^{\top} \begin{Bmatrix}\varepsilon_e\end{Bmatrix}}{2} dV$$

$$\Lambda=\int_V \frac{E\begin{Bmatrix}\varepsilon_e\end{Bmatrix}^{\top} \begin{Bmatrix}\varepsilon_e\end{Bmatrix}}{2} dV$$   

First we will split this equation up and use $\begin{Bmatrix}\varepsilon_e\end{Bmatrix}=\begin{Bmatrix}\varepsilon_{tot}\end{Bmatrix}-\begin{Bmatrix}\varepsilon_{0}\end{Bmatrix}$ to note that:
$$\frac{\varepsilon_{e}^2}{2}=\frac{(\varepsilon_{tot}-\varepsilon_{0})^2}{2}=\frac{\varepsilon_{tot}^2}{2}-\varepsilon_{0}\varepsilon_{tot}+\frac{\varepsilon_{0}^2}{2}$$  
Or for matrices: 
$$\frac{\begin{Bmatrix}\varepsilon_{e}\end{Bmatrix}^{\top} \begin{Bmatrix}\varepsilon_{e}\end{Bmatrix}}{2} =\frac{\begin{Bmatrix}\varepsilon_{tot}\end{Bmatrix}^{\top} \begin{Bmatrix}\varepsilon_{tot}\end{Bmatrix}}{2}-\begin{Bmatrix}\varepsilon_{tot}\end{Bmatrix}^{\top} \begin{Bmatrix}\varepsilon_{0}\end{Bmatrix}+\frac{\begin{Bmatrix}\varepsilon_{0}\end{Bmatrix}^{\top} \begin{Bmatrix}\varepsilon_{0}\end{Bmatrix}}{2}$$
Leading to: 
$$\Lambda=\int_V \frac{E\begin{Bmatrix}\varepsilon_{tot}\end{Bmatrix}^{\top} \begin{Bmatrix}\varepsilon_{tot}\end{Bmatrix}}{2} dV-\int_V E\begin{Bmatrix}\varepsilon_{tot}\end{Bmatrix}^{\top} \begin{Bmatrix}\varepsilon_{0}\end{Bmatrix} dV + \int_V \frac{E\begin{Bmatrix}\varepsilon_{0}\end{Bmatrix}^{\top} \begin{Bmatrix}\varepsilon_{0}\end{Bmatrix}}{2} dV=a-b+c$$ 



Using $\begin{Bmatrix}\varepsilon_{tot}\end{Bmatrix}=\begin{bmatrix} B \end{bmatrix}\begin{Bmatrix} u \end{Bmatrix}$, and $\big(\begin{bmatrix} B \end{bmatrix}\begin{Bmatrix} u \end{Bmatrix}\big)^{\top}=\begin{Bmatrix} u \end{Bmatrix}^{\top}\begin{bmatrix} B \end{bmatrix}^{\top}$ we can write: 

$$a=\int_V \frac{E\begin{Bmatrix}\varepsilon_{tot}\end{Bmatrix}^{\top} \begin{Bmatrix}\varepsilon_{tot}\end{Bmatrix}}{2} dV=\int_V \frac{E}{2}\begin{Bmatrix} u \end{Bmatrix}^{\top}\begin{bmatrix} B \end{bmatrix}^{\top} \begin{bmatrix} B \end{bmatrix}\begin{Bmatrix} u \end{Bmatrix} dV$$ 
$$ = \frac{1}{2} \begin{Bmatrix} u \end{Bmatrix}^{\top}  \int_V E\begin{bmatrix} B \end{bmatrix}^{\top} \begin{bmatrix} B \end{bmatrix} dV \begin{Bmatrix} u \end{Bmatrix} $$
$$ = \frac{1}{2}\begin{Bmatrix} u \end{Bmatrix}^{\top} \begin{bmatrix} K \end{bmatrix} \begin{Bmatrix} u \end{Bmatrix} $$


Using $\begin{Bmatrix}\varepsilon_{tot}\end{Bmatrix}=\begin{bmatrix} B \end{bmatrix}\begin{Bmatrix} u \end{Bmatrix}$, and $\big(\begin{bmatrix} B \end{bmatrix}\begin{Bmatrix} u \end{Bmatrix}\big)^{\top}=\begin{Bmatrix} u \end{Bmatrix}^{\top}\begin{bmatrix} B \end{bmatrix}^{\top}$ we can write: 

$$b=\int_V E\begin{Bmatrix}\varepsilon_{tot}\end{Bmatrix}^{\top} \begin{Bmatrix}\varepsilon_{0}\end{Bmatrix} dV=\int_V E \begin{Bmatrix} u \end{Bmatrix}^{\top}\begin{bmatrix} B \end{bmatrix}^{\top} \begin{Bmatrix}\varepsilon_{0}\end{Bmatrix} dV$$
$$=\begin{Bmatrix} u \end{Bmatrix}^{\top} \int_V \begin{bmatrix} B \end{bmatrix}^{\top} E \begin{Bmatrix}\varepsilon_{0}\end{Bmatrix} dV$$

Leading to: 
$$\Lambda=a-b+c=\frac{1}{2}\begin{Bmatrix} u \end{Bmatrix}^{\top} \begin{bmatrix} K \end{bmatrix} \begin{Bmatrix} u \end{Bmatrix}-\begin{Bmatrix} u \end{Bmatrix}^{\top}\int_V \begin{bmatrix} B \end{bmatrix}^{\top} E \begin{Bmatrix}\varepsilon_{0}\end{Bmatrix} dV + \int_V \frac{E\begin{Bmatrix}\varepsilon_{0}\end{Bmatrix}^{\top} \begin{Bmatrix}\varepsilon_{0}\end{Bmatrix}}{2} dV$$ 
  
Next recall solving for: 
$$\frac{\partial\Pi}{\partial \begin{Bmatrix} u \end{Bmatrix}}=0$$
With:
$$\partial\Pi=\Lambda-W$$
$$W=\begin{Bmatrix} u \end{Bmatrix}^\top\begin{Bmatrix} F \end{Bmatrix}$$

Leading to: 
$$\Lambda=a-b+c=\frac{1}{2}\begin{Bmatrix} u \end{Bmatrix}^{\top} \begin{bmatrix} K \end{bmatrix} \begin{Bmatrix} u \end{Bmatrix}-\begin{Bmatrix} u \end{Bmatrix}^{\top}\int_V \begin{bmatrix} B \end{bmatrix}^{\top} E \begin{Bmatrix}\varepsilon_{0}\end{Bmatrix} dV + \int_V \frac{E\begin{Bmatrix}\varepsilon_{0}\end{Bmatrix}^{\top} \begin{Bmatrix}\varepsilon_{0}\end{Bmatrix}}{2} dV$$ 
  
Next recall solving for: 
$$\frac{\partial\Pi}{\partial \begin{Bmatrix} u \end{Bmatrix}}=0=\begin{bmatrix} K \end{bmatrix} \begin{Bmatrix} u \end{Bmatrix}- \int_V \begin{bmatrix} B \end{bmatrix}^{\top} E \begin{Bmatrix}\varepsilon_{0}\end{Bmatrix} dV - \begin{Bmatrix} F \end{Bmatrix}$$
With:
$$\Pi=\Lambda-W$$
$$W=\begin{Bmatrix} u \end{Bmatrix}^\top \begin{Bmatrix} F \end{Bmatrix}$$

Rearranging $\frac{\partial\Pi}{\partial \begin{Bmatrix} u \end{Bmatrix}}$ gives: 

$$\begin{bmatrix} K \end{bmatrix} \begin{Bmatrix} u \end{Bmatrix} = \int_V \begin{bmatrix} B \end{bmatrix}^{\top} E \begin{Bmatrix}\varepsilon_{0}\end{Bmatrix} dV + \begin{Bmatrix} F \end{Bmatrix}$$
Next define $\begin{Bmatrix} F \end{Bmatrix}^{thermal}$: 
$$\begin{Bmatrix} F \end{Bmatrix}^{thermal} = \int_V \begin{bmatrix} B \end{bmatrix}^{\top} E \begin{Bmatrix}\varepsilon_{0}\end{Bmatrix} dV$$


Using $\begin{Bmatrix}\varepsilon_{0}\end{Bmatrix}=\alpha \Delta T$, $\begin{bmatrix} B \end{bmatrix}^\top =\begin{bmatrix} -\frac{1}{L} \\ \frac{1}{L}\end{bmatrix}$,and $dV=AdX$ we can rewrite $\begin{Bmatrix} F \end{Bmatrix}^{thermal}$: 

$$\begin{Bmatrix} F \end{Bmatrix}^{thermal}=\int_0^L \begin{bmatrix} -\frac{1}{L} \\ \frac{1}{L}\end{bmatrix} E \alpha \Delta T A dx $$

$$= \begin{bmatrix} -\frac{1}{L} \\ \frac{1}{L}\end{bmatrix} E \alpha \Delta T A \int_0^L dx = \begin{bmatrix} -\frac{1}{L} \\ \frac{1}{L}\end{bmatrix} E \alpha \Delta T A L $$

$$\begin{Bmatrix} F \end{Bmatrix}^{thermal}=E \alpha \Delta T A \begin{bmatrix} -1 \\ 1 \end{bmatrix}  $$



# The truss element (mechanical loads)
![spring](truss1.png)  

* Behaviour Hooke's law for a bar:    
$$\begin{Bmatrix} \sigma \end{Bmatrix}=E \begin{Bmatrix}\epsilon\end{Bmatrix}$$     
$$\begin{Bmatrix} f_{1} \\ f_{2} \end{Bmatrix}=\frac{AE}{L}\begin{bmatrix} 1 & -1 \\ -1 & 1\end{bmatrix}\begin{Bmatrix} u_1 \\ u_2\end{Bmatrix}$$   

* Truss (or bar) is a 1D element but has a **cross-sectional area** $A$    

* **strain** a relative metric for deformation: 
$$\begin{Bmatrix} \varepsilon \end{Bmatrix}= \begin{bmatrix} B \end{bmatrix}\begin{Bmatrix} u \end{Bmatrix}$$  


# The truss element (thermal loads)

## Adding termal strain
![spring](truss1.png)   

$$\begin{Bmatrix} f_{1} \\ f_{2} \end{Bmatrix}+E \alpha \Delta T A \begin{bmatrix} -1 \\ 1 \end{bmatrix} =\frac{AE}{L}\begin{bmatrix} 1 & -1 \\ -1 & 1\end{bmatrix}\begin{Bmatrix} u_1 \\ u_2\end{Bmatrix}$$  

Define a total strain $\varepsilon_{tot}$  and split into a thermal $\begin{Bmatrix}\varepsilon_{0}\end{Bmatrix}$ and mechanical (elastic) strain $\begin{Bmatrix}\varepsilon_{e}\end{Bmatrix}$: 
$$\begin{Bmatrix}\varepsilon_{tot}\end{Bmatrix}=\begin{Bmatrix}\varepsilon_e\end{Bmatrix}+\begin{Bmatrix}\varepsilon_0\end{Bmatrix}$$

$\alpha$: Thermal expansion coefficient   
$\Delta T$: Temperature change

# Example 1: Thermal loads in a contrained set of trusses
A 2 truss structure subjected to temperature variations  

![](trussSet_2_thermal_1.png)   

$$\begin{Bmatrix} f_{1} \\ f_{2} \end{Bmatrix}+E \alpha \Delta T A \begin{bmatrix} -1 \\ 1 \end{bmatrix} =\frac{AE}{L}\begin{bmatrix} 1 & -1 \\ -1 & 1\end{bmatrix}\begin{Bmatrix} u_1 \\ u_2\end{Bmatrix}$$  

$E_1=2000 N/m^2$, $A_1=1 m^2$, $L_1=10 m$, $\alpha_1=2\cdot10^{-6} / ^{\circ}C$  
$E_2=2000 N/m^2$, $A_2=0.5 m^2$, $L_2=8 m$, $\alpha_2=2\cdot10^{-6} / ^{\circ}C$   
$\Delta T$: Temperature change

Given that the neutral (zero force) temperature is 18 °C, determine the nodal displacements and forces at night and during the day. 

## Compute thermal forces

### Day situation
During the day $\Delta T=\Delta T_{day}=25-18=7$:   

$$\begin{Bmatrix} f_1^{(1)} \\ f_2^{(1)}  \end{Bmatrix}^{thermal} = E_1 \alpha_1 \Delta T_{day} A_1 \begin{bmatrix} -1 \\ 1 \end{bmatrix} = 2000 \cdot (2\cdot10^{-6}) \cdot 7 \cdot 1 \begin{bmatrix} -1 \\ 1 \end{bmatrix} = \begin{Bmatrix} -0.028 \\ 0.028 \end{Bmatrix}$$

$$\begin{Bmatrix} f_2^{(2)} \\ f_3^{(2)}  \end{Bmatrix}^{thermal} = E_2 \alpha_2 \Delta T_{day} A_2 \begin{bmatrix} -1 \\ 1 \end{bmatrix} = 2000 \cdot (2\cdot10^{-6}) \cdot 7 \cdot 0.5 \begin{bmatrix} -1 \\ 1 \end{bmatrix} = \begin{Bmatrix} -0.014 \\ 0.014 \end{Bmatrix}$$

Superposition: 
$$\begin{Bmatrix} F  \end{Bmatrix}^{thermal} = \begin{Bmatrix} -0.028 \\ 0.028-0.014 \\ 0.014 \end{Bmatrix}= \begin{Bmatrix} -0.028 \\ 0.014 \\ 0.014 \end{Bmatrix}$$


### Night situation
During the night $\Delta T=\Delta T_{night}=-2-18=-20$:   

$$\begin{Bmatrix} f_1^{(1)} \\ f_2^{(1)}  \end{Bmatrix}^{thermal} = E_1 \alpha_1 \Delta T_{day} A_1 \begin{bmatrix} -1 \\ 1 \end{bmatrix} = 2000 \cdot (2\cdot10^{-6}) \cdot -20 \cdot 1 \begin{bmatrix} -1 \\ 1 \end{bmatrix} = \begin{Bmatrix} 0.08 \\ -0.08 \end{Bmatrix}$$

$$\begin{Bmatrix} f_2^{(2)} \\ f_3^{(2)}  \end{Bmatrix}^{thermal} = E_2 \alpha_2 \Delta T_{day} A_2 \begin{bmatrix} -1 \\ 1 \end{bmatrix} = 2000 \cdot (2\cdot10^{-6}) \cdot -20 \cdot 0.5 \begin{bmatrix} -1 \\ 1 \end{bmatrix} = \begin{Bmatrix} 0.04 \\ -0.04 \end{Bmatrix}$$

Superposition: 
$$\begin{Bmatrix} F  \end{Bmatrix}^{thermal} = \begin{Bmatrix} 0.08 \\ -0.08+0.04 \\ -0.04 \end{Bmatrix}= \begin{Bmatrix} 0.08 \\ -0.04 \\ -0.04 \end{Bmatrix}$$

In [64]:
E1=2000; A1=1;   L1=10; a1=2e-6;
E2=2000; A2=0.5; L2=8;  a2=2e-6;
T_neutral=18;
T_day=25;
T_night=-2;
dT_day=T_day-T_neutral;
dT_night=T_night-T_neutral
f12_day   = E1*a1*dT_day*A1*[-1;1]
f23_day   = E2*a2*dT_day*A2*[-1;1]
f12_night = E1*a1*dT_night*A1*[-1;1]
f23_night = E2*a2*dT_night*A2*[-1;1]

dT_night = -20
f12_day =

  -0.028000
   0.028000

f23_day =

  -0.014000
   0.014000

f12_night =

   0.080000
  -0.080000

f23_night =

   0.040000
  -0.040000



## Set up element stiffness matrices

$$ \begin{bmatrix} K^{(1)} \end{bmatrix}=\frac{A_1 E_1}{L_1}\begin{bmatrix} 1 & -1 \\ -1 & 1\end{bmatrix}=\frac{1 \cdot 2000}{10}\begin{bmatrix} 1 & -1 \\ -1 & 1\end{bmatrix}=\begin{bmatrix} 200 & -200 \\ -200 & 200\end{bmatrix}$$  

$$ \begin{bmatrix} K^{(2)} \end{bmatrix}=\frac{A_2 E_2}{L_2}\begin{bmatrix} 1 & -1 \\ -1 & 1\end{bmatrix}=\frac{0.5 \cdot 2000}{8}\begin{bmatrix} 1 & -1 \\ -1 & 1\end{bmatrix}=\begin{bmatrix} 125 & -125 \\ -125 & 125\end{bmatrix}$$  



In [65]:
% Numerical check
k1=(A1*E1)./L1;
k2=(A2*E2)./L2;
Q=[1 -1; -1 1];
K1=k1*Q
K2=k2*Q

K1 =

   200  -200
  -200   200

K2 =

   125  -125
  -125   125



## Use superposition to assemble total stiffness matrix
$$\begin{bmatrix} K \end{bmatrix}=\underbrace{\begin{bmatrix} 200 & -200 & 0 \\ -200 & 200 & 0 \\ 0 & 0 & 0\end{bmatrix}}_{\begin{bmatrix} K^{(1)} \end{bmatrix}}+\underbrace{\begin{bmatrix} 0 & 0 & 0 \\ 0 & 125 & -125 \\ 0 & -125 & 125\end{bmatrix}}_{\begin{bmatrix} K^{(2)} \end{bmatrix}}=\begin{bmatrix} 200 & -200 & 0 \\ -200 & 325 & -125 \\ 0 & -125 & 125\end{bmatrix}$$  


In [66]:
% Numerical check
K=zeros(3,3);
K(1:2,1:2)=K(1:2,1:2)+K1;
K(2:3,2:3)=K(2:3,2:3)+K2

K =

   200  -200     0
  -200   325  -125
     0  -125   125



## Solving for unknown forces and displacements during day

$$\begin{Bmatrix} F \end{Bmatrix}+\begin{Bmatrix} F \end{Bmatrix}^{thermal}=\begin{bmatrix} K \end{bmatrix}\begin{Bmatrix} u \end{Bmatrix}$$   

$$\begin{Bmatrix} F_1 \\ 0 \\ F_3 \end{Bmatrix}+\begin{Bmatrix} f_1^{(1)} \\ f_2^{(1)}+f_2^{(2)} \\ f_3^{(2)} \end{Bmatrix}^{thermal}=\begin{bmatrix} 200 & -200 & 0 \\ -200 & 325 & -125 \\ 0 & -125 & 125\end{bmatrix}\begin{Bmatrix} 0 \\ u_2 \\ 0 \end{Bmatrix}$$  

$$\begin{Bmatrix} F_1 \\ 0 \\ F_3 \end{Bmatrix}+\begin{Bmatrix} -0.028 \\ 0.014 \\ 0.014 \end{Bmatrix}=\begin{bmatrix} 200 & -200 & 0 \\ -200 & 325 & -125 \\ 0 & -125 & 125\end{bmatrix}\begin{Bmatrix} 0 \\ u_2 \\ 0 \end{Bmatrix}$$   
  
$$\rightarrow 0.014=325*u_2 \rightarrow u_2=\frac{0.014}{325}\approx 4.308\cdot10^{-5}$$  


In [69]:
% Numerical check
F_thermal_day=zeros(3,1);
F_thermal_day(1:2)=F_thermal_day(1:2)+f12_day;
F_thermal_day(2:3)=F_thermal_day(2:3)+f23_day
F2=0+F_thermal_day(2)
u2=F2./K(2,2)

F_thermal_day =

  -0.028000
   0.014000
   0.014000

F2 =  0.014000
u2 =  0.000043077


$$\begin{Bmatrix} F_1 \\ 0 \\ F_3 \end{Bmatrix}+\begin{Bmatrix} -0.028 \\ 0.014 \\ 0.014 \end{Bmatrix}=\begin{bmatrix} 200 & -200 & 0 \\ -200 & 325 & -125 \\ 0 & -125 & 125\end{bmatrix}\begin{Bmatrix} 0 \\ u_2 \\ 0 \end{Bmatrix}$$   
  
$$\rightarrow F_1-0.028=-200*u_2 \rightarrow F_1=-200 \cdot \frac{0.014}{325}+0.028 \approx 0.01939$$  
$$\rightarrow F_3+0.014=-125*u_2 \rightarrow F_3=-125 \cdot \frac{0.014}{325}-0.014 \approx -0.01939$$  


In [54]:
u=[0 u2 0]' %Displacements
F_total=K*u %Total forces
F=F_total-F_thermal_day %Direct forces

u =

   0.000000000
   0.000043077
   0.000000000

F_total =

  -0.0086154
   0.0140000
  -0.0053846

F =

   0.019385
   0.000000
  -0.019385



## Solving for unknown forces and displacements during night

$$\begin{Bmatrix} F \end{Bmatrix}+\begin{Bmatrix} F \end{Bmatrix}^{thermal}=\begin{bmatrix} K \end{bmatrix}\begin{Bmatrix} u \end{Bmatrix}$$   

$$\begin{Bmatrix} F_1 \\ 0 \\ F_3 \end{Bmatrix}+\begin{Bmatrix} f_1^{(1)} \\ f_2^{(1)}+f_2^{(2)} \\ f_3^{(2)} \end{Bmatrix}^{thermal}=\begin{bmatrix} 200 & -200 & 0 \\ -200 & 325 & -125 \\ 0 & -125 & 125\end{bmatrix}\begin{Bmatrix} 0 \\ u_2 \\ 0 \end{Bmatrix}$$  

$$\begin{Bmatrix} F_1 \\ 0 \\ F_3 \end{Bmatrix}+\begin{Bmatrix} 0.08 \\ -0.04 \\ -0.04 \end{Bmatrix}=\begin{bmatrix} 200 & -200 & 0 \\ -200 & 325 & -125 \\ 0 & -125 & 125\end{bmatrix}\begin{Bmatrix} 0 \\ u_2 \\ 0 \end{Bmatrix}$$   
  
$$\rightarrow -0.04=325*u_2 \rightarrow u_2=\frac{-0.04}{325}\approx -12.31\cdot10^{-5}$$  


In [55]:
% Numerical check
F_thermal_night=zeros(3,1);
F_thermal_night(1:2)=F_thermal_night(1:2)+f12_night
F_thermal_night(2:3)=F_thermal_night(2:3)+f23_night

F2=0+F_thermal_night(2)
u2=F2./K(2,2)

F_thermal_night =

   0.080000
  -0.080000
   0.000000

F_thermal_night =

   0.080000
  -0.040000
  -0.040000

F2 = -0.040000
u2 = -0.00012308


$$\begin{Bmatrix} F_1 \\ 0 \\ F_3 \end{Bmatrix}+\begin{Bmatrix} 0.08 \\ -0.04 \\ -0.04 \end{Bmatrix}=\begin{bmatrix} 200 & -200 & 0 \\ -200 & 325 & -125 \\ 0 & -125 & 125\end{bmatrix}\begin{Bmatrix} 0 \\ u_2 \\ 0 \end{Bmatrix}$$   
  
$$\rightarrow F_1+0.08=-200*u_2 \rightarrow F_1=-200 \cdot \frac{-0.04}{325}-0.08 \approx -0.05539$$  
$$\rightarrow F_3-0.04=-125*u_2 \rightarrow F_1=-125 \cdot \frac{-0.04}{325}+0.04 \approx 0.05539$$  


In [56]:
u=[0 u2 0]' %Displacements
F_total=K*u %Total forces
F=F_total-F_thermal_night %Direct forces

u =

   0.00000000
  -0.00012308
   0.00000000

F_total =

   0.024615
  -0.040000
   0.015385

F =

  -0.055385
   0.000000
   0.055385



# Question 2 thermal loads in a partially constrained set of trusses
Consider the two truss system of Figure Q2. Both trusses are linear elastic. The first node is constrained from moving. Node 3 is subjected to a direct nodal force of $P=20$ N (in the x-direction).  Furthermore, the system is heated, from an initial temperature of 18° Celsius, to 100° Celsius. The truss parameters for all elements are given in Table Q2.

|   | Element 1 | Element 2 |
| ----------- | ----------- | ----------- |
| Youngs modulus | 100 MPa | 100 MPa |
| Area | 50 $mm^2$ | 25 $mm^2$ |
| Length | 250 mm | 200 mm | 
| Thermal exp. coeff. | 2x$10^{-4}$/° Celsius | 2x$10^{-4}$/° Celsius | 

__(a)__ The increase in temperature causes thermal expansion and forces to develop in the truss system. Compute the element thermal force arrays as well as the global thermal force array. 

__(b)__ Derive the element stiffness matrices as well as the global stiffness matrix.

__(c)__ Formulate the finite element equations for this system and use the finite element method to compute the nodal displacements and the direct nodal forces.

__(d)__ Use the truss shape functions to compute the displacement in truss 1 at x=125 mm, assuming node 1 is at x=0 mm.

__(e)__ Use the B-matrix to compute the element strains.

![](trussSet_2_thermal_uncontrained.png)   


## Solution (a)

Compute the temperature change: 
$$\Delta T=100-18=82$$   

Compute thermal force contributions:   
$$\begin{Bmatrix} f_1^{(1)} \\ f_2^{(1)}  \end{Bmatrix}^{thermal} = E_1 \alpha_1 \Delta T A_1 \begin{bmatrix} -1 \\ 1 \end{bmatrix} = 100 \cdot (2\cdot10^{-4}) \cdot 82 \cdot 50 \begin{bmatrix} -1 \\ 1 \end{bmatrix} = \begin{Bmatrix} -82 \\ 82 \end{Bmatrix}$$

$$\begin{Bmatrix} f_2^{(2)} \\ f_3^{(2)}  \end{Bmatrix}^{thermal} = E_2 \alpha_2 \Delta T A_2 \begin{bmatrix} -1 \\ 1 \end{bmatrix} = 100 \cdot (2\cdot10^{-4}) \cdot 82 \cdot 25 \begin{bmatrix} -1 \\ 1 \end{bmatrix} = \begin{Bmatrix} -41 \\ 41 \end{Bmatrix}$$

Use superposition to get total thermal force contribution: 
$$\begin{Bmatrix} F  \end{Bmatrix}^{thermal} = \begin{Bmatrix} -82 \\ 82-41 \\ 41 \end{Bmatrix}= \begin{Bmatrix} -82 \\ 41 \\ 41 \end{Bmatrix}$$


In [57]:
% Numerical check
E1=100; A1=50; L1=250; a1=2e-4;
E2=100; A2=25; L2=200; a2=2e-4;
T_neutral=18; T=100; dT=T-T_neutral;

f12 = E1*a1*dT*A1*[-1;1]
f23 = E2*a2*dT*A2*[-1;1]

F_th=zeros(3,1);
F_th(1:2)=f12+F_th(1:2);
F_th(2:3)=f23+F_th(2:3)

f12 =

  -82
   82

f23 =

  -41
   41

F_th =

  -82
   41
   41



## Solution (b)

Set up element stiffness matrices

$$ \begin{bmatrix} K^{(1)} \end{bmatrix}=\frac{A_1 E_1}{L_1}\begin{bmatrix} 1 & -1 \\ -1 & 1\end{bmatrix}=\frac{50 \cdot 100}{250}\begin{bmatrix} 1 & -1 \\ -1 & 1\end{bmatrix}=\begin{bmatrix} 20 & -20 \\ -20 & 20\end{bmatrix}$$  

$$ \begin{bmatrix} K^{(2)} \end{bmatrix}=\frac{A_2 E_2}{L_2}\begin{bmatrix} 1 & -1 \\ -1 & 1\end{bmatrix}=\frac{25 \cdot 100}{200}\begin{bmatrix} 1 & -1 \\ -1 & 1\end{bmatrix}=\begin{bmatrix} 12.5 & -12.5 \\ -12.5 & 12.5\end{bmatrix}$$  

Use superposition to assemble total stiffness matrix
$$\begin{bmatrix} K \end{bmatrix}=\underbrace{\begin{bmatrix} 20 & -20 & 0 \\ -20 & 20 & 0 \\ 0 & 0 & 0\end{bmatrix}}_{\begin{bmatrix} K^{(1)} \end{bmatrix}}+\underbrace{\begin{bmatrix} 0 & 0 & 0 \\ 0 & 12.5 & -12.5 \\ 0 & -12.5 & 12.5\end{bmatrix}}_{\begin{bmatrix} K^{(2)} \end{bmatrix}}=\begin{bmatrix} 20 & -20 & 0 \\ -20 & 32.5 & -12.5 \\ 0 & -12.5 & 12.5\end{bmatrix}$$  

In [58]:
% Numerical check
K1=(A1*E1)/L1*[1 -1; -1 1]
K2=(A2*E2)/L2*[1 -1; -1 1]
K=zeros(3,3);
K(1:2,1:2)=K(1:2,1:2)+K1;
K(2:3,2:3)=K(2:3,2:3)+K2

K1 =

   20  -20
  -20   20

K2 =

   12.500  -12.500
  -12.500   12.500

K =

   20.00000  -20.00000    0.00000
  -20.00000   32.50000  -12.50000
    0.00000  -12.50000   12.50000



## Solution (c)

The total system of equations is written as: 

$$\begin{Bmatrix} F \end{Bmatrix}+\begin{Bmatrix} F \end{Bmatrix}^{thermal}=\begin{bmatrix} K \end{bmatrix}\begin{Bmatrix} u \end{Bmatrix}$$   

Leading to: 

$$\begin{Bmatrix} F_1 \\ 0 \\ 20 \end{Bmatrix}+\begin{Bmatrix} -82 \\ 41 \\ 41 \end{Bmatrix}=\begin{bmatrix} 20 & -20 & 0 \\ -20 & 32.5 & -12.5 \\ 0 & -12.5 & 12.5\end{bmatrix}\begin{Bmatrix} 0 \\ u_2 \\ u_3 \end{Bmatrix}$$  

Providing the following equations:
$$ \rightarrow 32.5 \cdot u_2-12.5 \cdot u_3 =41 $$  
$$ \rightarrow -12.5 \cdot u_2+12.5 \cdot u_3 =61 $$  


Leading to: 
$$ \rightarrow 20 \cdot u_2=102 $$  
$$ \rightarrow u_2=\frac{102}{20}=\frac{51}{10}=5.1 $$ 

And therefore: 
$$ \rightarrow 32.5 \cdot u_2-12.5 \cdot u_3 =41 $$  
$$ \rightarrow 32.5 \cdot 5.1-12.5 \cdot u_3 =41 $$  
$$ \rightarrow -12.5 \cdot u_3 =41-165.75=-124.75 $$  
$$ \rightarrow u_3 =\frac{-124.75}{-12.5}=9.98 $$  

Leading to: 
$$\begin{Bmatrix} F_1 \\ 0 \\ 20 \end{Bmatrix}+\begin{Bmatrix} -82 \\ 41 \\ 41 \end{Bmatrix}=\begin{bmatrix} 20 & -20 & 0 \\ -20 & 32.5 & -12.5 \\ 0 & -12.5 & 12.5\end{bmatrix}\begin{Bmatrix} 0 \\ 5.1 \\ 9.98 \end{Bmatrix}=\begin{Bmatrix} -102 \\ 41 \\ 61 \end{Bmatrix}$$ 

And therefore $F_1=-20$ since: 
$$\begin{Bmatrix} F_1 \\ 0 \\ 20 \end{Bmatrix}+\begin{Bmatrix} -82 \\ 41 \\ 41 \end{Bmatrix}=\begin{Bmatrix} -102 \\ 41 \\ 61 \end{Bmatrix}=\begin{Bmatrix} -20 \\ 0 \\ 20 \end{Bmatrix}+\begin{Bmatrix} -82 \\ 41 \\ 41 \end{Bmatrix}$$

In [59]:
% Numerical check
F2=0; %Force in middle node is zero
F3=20; %The applied force to node 3
u2=((F2+F_th(2))+(F3+F_th(3)))/(K(2,2)+K(3,2)) %Displacement u2
u3=((F2+F_th(2))-(K(2,2).*u2))./K(2,3) %Displacement u3

u=[0 u2 u3]' %Displacements
F_tot=K*u %Compute total force
F1=F_tot(1,1)-F_th(1,1) %get F1

u2 =  5.1000
u3 =  9.9800
u =

   0.00000
   5.10000
   9.98000

F_tot =

  -102.000
    41.000
    61.000

F1 = -20


## Solution (d)

The coordinate $x=125$ mm is in element 1 (in fact it is in the middle). The truss shape functions for this element can be expressed as: 
$$\begin{bmatrix} \mathbf{N}^{(1)} \end{bmatrix}=\begin{bmatrix} 1-\frac{x}{L_1} & \frac{x}{L_1}\end{bmatrix}=\begin{bmatrix} 1-\frac{125}{250} & \frac{125}{250}\end{bmatrix}$$
Shape function based displacement interpolation is written as: 
$$u(x)=\begin{bmatrix} \mathbf{N} \end{bmatrix} \begin{Bmatrix} \mathbf{u} \end{Bmatrix}=\begin{bmatrix} 0.5 & 0.5 \end{bmatrix} \begin{Bmatrix} 0 \\ 5.1 \end{Bmatrix}=2.55$$

In [60]:
% Numerical check
x=125; %X-coordinate for interpolation
N=[1-x/L1 x/L1] %Shape function metrics
u %Displacement vector
ux=N*u([1 2]) %Interpolated displacement

N =

   0.50000   0.50000

u =

   0.00000
   5.10000
   9.98000

ux =  2.5500


## Solution (e)

The $\begin{bmatrix} \mathbf{B} \end{bmatrix}$ matrix is expressed as: 

$$\begin{bmatrix} \mathbf{B} \end{bmatrix}=\begin{bmatrix} -\frac{1}{L} & \frac{1}{L} \end{bmatrix} $$

and the strain can be computed from; 
$$\varepsilon^{(i)}=\begin{bmatrix} B \end{bmatrix}^{(i)} \begin{Bmatrix} \mathbf{u} \end{Bmatrix}^{(i)}$$

For element 1 we have: 
$$\varepsilon^{(1)}=\begin{bmatrix} -\frac{1}{250} & \frac{1}{250} \end{bmatrix} \begin{Bmatrix} 0 \\ 5.1 \end{Bmatrix}=0.0204$$

For element 2 we have: 
$$\varepsilon^{(2)}=\begin{bmatrix} -\frac{1}{200} & \frac{1}{200} \end{bmatrix} \begin{Bmatrix} 5.1 \\ 9.98\end{Bmatrix}=0.0244$$

In [61]:
% Numerical check
B1=[-1/L1 1/L1];
u_e1=u([1 2]);
eps_1=B1*u_e1

B2=[-1/L2 1/L2];
u_e2=u([2 3]);
eps_2=B2*u_e2

eps_1 =  0.020400
eps_2 =  0.024400


# Summary

* To allow for thermal strains the total strain $\begin{Bmatrix}\varepsilon\end{Bmatrix}$ is decomposed into the elastic strain $\begin{Bmatrix}\varepsilon_e\end{Bmatrix}$ and the termal strain $\begin{Bmatrix}\varepsilon_0\end{Bmatrix}$:
$$\begin{Bmatrix}\varepsilon_{tot}\end{Bmatrix}=\begin{Bmatrix}\varepsilon_e\end{Bmatrix}+\begin{Bmatrix}\varepsilon_0\end{Bmatrix}$$
$$\begin{Bmatrix}\varepsilon_e\end{Bmatrix}=\begin{Bmatrix}\varepsilon_{tot}\end{Bmatrix}-\begin{Bmatrix}\varepsilon_{0}\end{Bmatrix}$$    
  
  
* The truss equations featuring thermal effects were developed as:  
$$\begin{Bmatrix} f_{1} \\ f_{2} \end{Bmatrix}+E \alpha \Delta T A \begin{bmatrix} -1 \\ 1 \end{bmatrix} =\frac{AE}{L}\begin{bmatrix} 1 & -1 \\ -1 & 1\end{bmatrix}\begin{Bmatrix} u_1 \\ u_2\end{Bmatrix}$$  

With:  
 
$\alpha$: Thermal expansion coefficient   
$\Delta T$: Temperature change


\newpage

**About this document**    

This document was created using a [Jupyter notebook](https://jupyter.org/) which allows for the presentation of theory and equations, as well as live (running code) numerical implementations. 

This Jupyter notebook is available [open source](https://github.com/Kevin-Mattheus-Moerman/NUIG_BME_402_6101) and features the [Octave](https://www.gnu.org/software/octave/index) programming language (an open source alternative to MATLAB). If you are interested in running this Jupyter notebook yourself [download and install Octave](https://www.gnu.org/software/octave/download) and install [the Jupyter environment](https://jupyter.org/install). Once both Jupyter and Octave are installed follow [these instructions](https://github.com/calysto/octave_kernel) to configure the use of Octave with Jupyter notebooks. 

To run Jupyter call `jupyter notebook` from your Terminal/Command Prompt. 